version: '3.8'
services:
  cinext-recommendation-api:
    build: .
    env_file:
      - .env
    image: cinext-recommendation-api
    container_name: cinext-recommendation-api
    restart: unless-stopped
    # Allow port when running on localhost, turn off port when running Caddy server
    # ports:
    #   - "8000:80"

  caddy:
    image: caddy/caddy:2.2.1-alpine
    container_name: caddy-service
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: